routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/* index  */
Route::get("/", array("as" => "index", "uses" => "HomeController@index"));


/*Post*/
Route::get("/posts", array("as" => "post.index", "uses" => "PostController@index"));
Route::get("/post/create", array("as" => "post.create", "uses" => "PostController@create"));
Route::post("/post", array("as" => "post.store", "uses" => "PostController@store"));
Route::get("/post/{id}", array("as" => "post.show", "uses" => "PostController@show"));
Route::get("/post/edit/{id}", array("as" => "post.edit", "uses" => "PostController@edit"));
Route::put("/post/{id}", array("as" => "post.update", "uses" => "PostController@update"));
Route::delete("/post/{id}", array("as" => "post.destroy", "uses" => "PostController@destroy"));
Route::get("/post/restore/{id}", array("as" => "post.restore", "uses" => "PostController@restore"));
Route::get("/post/{id}/status/{status}", array("as" => "post.status", "uses" => "PostController@changeStatus"));
Route::get("/post/{id}/promoted/{promoted}", array("as" => "post.promoted", "uses" => "PostController@changePromote"));
Route::get("/post/{id}/sticky/{sticky}", array("as" => "post.sticky", "uses" => "PostController@changeSticky"));
Route::get("/post/duplicate/{id}", array("as" => "post.duplicate", "uses" => "PostController@duplicate"));
Route::post("/post/actions", array("as" => "post.actions", "uses" => "PostController@actions"));


/*Category*/
Route::get("/categories", array("as" => "category.index", "uses" => "CategoryController@index"));
Route::post("/category", array("as" => "category.store", "uses" => "CategoryController@store"));
Route::get("/category/{id}", array("as" => "category.show", "uses" => "CategoryController@show"));
Route::get("/category/edit/{id}", array("as" => "category.edit", "uses" => "CategoryController@edit"));
Route::put("/category/{id}", array("as" => "category.update", "uses" => "CategoryController@update"));
Route::delete("/category/{id}", array("as" => "category.destroy", "uses" => "CategoryController@destroy"));
Route::get("/category/{id}/status/{status}", array("as" => "category.status", "uses" => "CategoryController@changeStatus"));
Route::post("/category/actions", array("as" => "category.actions", "uses" => "CategoryController@actions"));


/* Pubs  */
Route::get("/pubs", array("as" => "pub.index", "uses" => "PubController@index"));
Route::post("/pub", array("as" => "pub.store", "uses" => "PubController@store"));
Route::get("/pub/edit/{id}", array("as" => "pub.edit", "uses" => "PubController@edit"));
Route::post("/pub/translations/{id}", array("as" => "pub.store", "uses" => "PubController@translations"));
Route::put("/pub/{id}", array("as" => "pub.update", "uses" => "PubController@update"));
Route::delete("/pub/{id}", array("as" => "pub.destroy", "uses" => "PubController@destroy"));
Route::get("/pub/restore/{id}", array("as" => "pub.restore", "uses" => "PubController@restore"));
Route::get("/pub/{id}/status/{status}", array("as" => "pub.status", "uses" => "PubController@changeStatus"));
Route::post("/pub/actions", array("as" => "pub.actions", "uses" => "PubController@actions"));


/* Comment  */
Route::get("/comments", array("as" => "comment.index", "uses" => "CommentController@index"));
Route::get("/comment/create", array("as" => "comment.create", "uses" => "CommentController@create"));
Route::post("/comment", array("as" => "comment.store", "uses" => "CommentController@store"));
Route::post("/comment/translations/{id}", array("as" => "comment.store", "uses" => "CommentController@translations"));
Route::get("/comment/edit/{id}", array("as" => "comment.edit", "uses" => "CommentController@edit"));
Route::put("/comment/{id}", array("as" => "comment.update", "uses" => "CommentController@update"));
Route::delete("/comment/{id}", array("as" => "comment.destroy", "uses" => "CommentController@destroy"));
Route::get("/comment/restore/{id}", array("as" => "comment.restore", "uses" => "CommentController@restore"));
Route::get("/comment/{id}/status/{status}", array("as" => "comment.status", "uses" => "CommentController@changeStatus"));
Route::post("/comment/actions", array("as" => "comment.actions", "uses" => "CommentController@actions"));


/*  Language */
Route::get("/languages", array("as" => "language.index", "uses" => "LanguageController@index"));
Route::post("/language", array("as" => "language.store", "uses" => "LanguageController@store"));
Route::get("/language/edit/{id}", array("as" => "language.edit", "uses" => "LanguageController@edit"));
Route::put("/language/{id}", array("as" => "language.update", "uses" => "LanguageController@update"));
Route::delete("/language/{id}", array("as" => "language.destroy", "uses" => "LanguageController@destroy"));
Route::post("/language/actions", array("as" => "language.actions", "uses" => "LanguageController@actions"));
Route::get("/language/{id}/status/{status}", array("as" => "language.status", "uses" => "LanguageController@changeStatus"));


/* Menu  */
Route::get("/menus", array("as" => "menu.index", "uses" => "MenuController@index"));
Route::post("/menu", array("as" => "menu.store", "uses" => "MenuController@store"));
Route::get("/menu/{id}", array("as" => "menu.show", "uses" => "MenuController@show"));
Route::get("/menu/edit/{id}", array("as" => "menu.edit", "uses" => "MenuController@edit"));
Route::put("/menu/{id}", array("as" => "menu.update", "uses" => "MenuController@update"));
Route::delete("/menu/{id}", array("as" => "menu.destroy", "uses" => "MenuController@destroy"));
Route::get("/menu/{id}/status/{status}", array("as" => "menu.status", "uses" => "MenuController@changeStatus"));



Route::post("/link", array("as" => "link.store", "uses" => "MenuController@storeLink"));
Route::get("/link/edit/{id}", array("as" => "link.edit", "uses" => "MenuController@editLink"));
Route::put("/link/{id}", array("as" => "link.update", "uses" => "MenuController@updateLink"));
Route::delete("/link/{id}", array("as" => "link.destroy", "uses" => "MenuController@destroyLink"));
Route::post("/link/get-items", array("as" => "link.get.items", "uses" => "MenuController@getItems"));


/* Media  */
Route::get("/medias", array("as" => "media.index", "uses" => "MediaController@index"));
Route::get("/medias/clear-folder/{folder}", array("as" => "media.clear.folder", "uses" => "MediaController@clearFolder"));
Route::get("/medias/clear-medias/{folder}", array("as" => "media.clear.medias", "uses" => "MediaController@clearMedias"));
Route::post("/medias/upload", array("as" => "medias.upload", "uses" => "MediaController@upload"));
Route::post("/file/upload", array("as" => "file.upload", "uses"  => "MediaController@uploadFile"));
Route::post("/medias/upload-file", array("as" => "medias.upload.file", "uses" => "MediaController@uploadFile"));
Route::post("/images/ckupload", array("as" => "article.ckupload", "uses" => "MediaController@ckuploadImages"));
Route::put("/media/{id}", array("as" => "media.update", "uses" => "MediaController@update"));
Route::delete("/media/{id}", array("as" => "media.destroy", "uses" => "MediaController@destroy"));


/* Message  */
Route::get("/messages", array("as" => "message.index", "uses" => "MessageController@index"));
Route::get("/message/{id}", array("as" => "message.show", "uses" => "MessageController@show"));
Route::delete("/message/{id}", array("as" => "message.destroy", "uses" => "MessageController@destroy"));
Route::get("/message/{id}/viewed/{viewed}", array("as" => "message.viewed", "uses" => "MessageController@changeViewed"));
Route::post("/message/actions", array("as" => "message.actions", "uses" => "MessageController@actions"));


/* Page  */
Route::get("/pages", array("as" => "page.index", "uses" => "PageController@index"));
Route::get("/page/create", array("as" => "page.create", "uses" => "PageController@create"));
Route::post("/page", array("as" => "page.store", "uses" => "PageController@store"));
Route::post("/page/translations/{id}", array("as" => "page.store", "uses" => "PageController@translations"));
Route::get("/page/edit/{id}", array("as" => "page.edit", "uses" => "PageController@edit"));
Route::put("/page/{id}", array("as" => "page.update", "uses" => "PageController@update"));
Route::delete("/page/{id}", array("as" => "page.destroy", "uses" => "PageController@destroy"));
Route::get("/page/restore/{id}", array("as" => "page.restore", "uses" => "PageController@restore"));
Route::get("/page/{id}/status/{status}", array("as" => "page.status", "uses" => "PageController@changeStatus"));
Route::post("/page/actions", array("as" => "page.actions", "uses" => "PageController@actions"));

/*Poll*/
Route::get("/polls", array("as" => "poll.index", "uses" => "PollController@index"));
Route::get("/poll/create", array("as" => "poll.create", "uses" => "PollController@create"));
Route::post("/poll", array("as" => "poll.store", "uses" => "PollController@store"));
Route::get("/poll/{id}", array("as" => "poll.show", "uses" => "PollController@show"));
Route::get("/poll/edit/{id}", array("as" => "poll.edit", "uses" => "PollController@edit"));
Route::put("/poll/{id}", array("as" => "poll.update", "uses" => "PollController@update"));
Route::delete("/poll/{id}", array("as" => "poll.destroy", "uses" => "PollController@destroy"));
Route::get("/poll/restore/{id}", array("as" => "poll.restore", "uses" => "PollController@restore"));
Route::get("/poll/{id}/status/{status}", array("as" => "poll.status", "uses" => "PollController@changeStatus"));
Route::get("/poll/{id}/promoted/{promoted}", array("as" => "poll.promoted", "uses" => "PollController@changePromote"));
Route::get("/poll/{id}/sticky/{sticky}", array("as" => "poll.sticky", "uses" => "PollController@changeSticky"));
Route::get("/poll/duplicate/{id}", array("as" => "poll.duplicate", "uses" => "PollController@duplicate"));
Route::post("/poll/actions", array("as" => "poll.actions", "uses" => "PollController@actions"));


/* Setting  */

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Spatie\Honeypot\ProtectAgainstSpam;
/* index  */

Route::get("/", array("as" => "index", "uses" => "HomeController@index"));

/* search  */
Route::get("/search", array("as" => "search", "uses" => "SearchController@show"));


/*Post*/
Route::get("/blog", array("as" => "blog", "uses" => "PostController@index"));
Route::get("/post/{slug}", array("as" => "blog.show", "uses" => "PostController@show"));
/*Post*/
Route::get("/portfolio", array("as" => "portfolio", "uses" => "PostController@portfolioIndex"));
Route::get("/portfolio/{slug}", array("as" => "portfolio.show", "uses" => "PostController@portfolioShow"));


/* Page  */
Route::get("/about", array("as" => "about", "uses" => "PageController@about"));
Route::get("/faq", array("as" => "faq", "uses" => "PageController@faq"));
Route::get("/services", array("as" => "services", "uses" => "PageController@services"));
Route::get("/sitemap", array("as" => "sitemap", "uses" => "PageController@sitemap"));
Route::get("/contact", array("as" => "contact", "uses" => "PageController@contact"));
Route::post("/contact", array("as" => "store.contact", "uses" => "PageController@storeMessage"))->middleware(ProtectAgainstSpam::class);


Route::middleware(["auth:sanctum", "verified"])->get("/dashboard", function () {
    return view("dashboard");
})->name("dashboard");

app/Models/Page.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Heroicpixels\Filterable\FilterableTrait;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Page extends Model
{
    use FilterableTrait, SoftDeletes, Sluggable, HasFactory;

    protected $dates = ["deleted_at"];

    public function sluggable(): array
    {
        return [
            "slug" => [
                "source" => "name"
            ]
        ];
    }

    public function toArray()
    {
        $array = parent::ToArray();
        $array["created_at"] = $this->getDate();
        return $array;
    }

    public function getDate()
    {
        if ($this->created_at) {
            return $this->created_at->format("d-m-y");
        } else {
            return "";
        }
    }

    /**
     * Get the language of the  article.
     */
    public function  language()
    {
        return $this->belongsTo("Waavi\Translation\Models\Language");
    }
}

resources/views/portfolio/index.blade.php
@extends('layouts.app')
@section('meta')
<title>{{trans('text.portfolio-index-title')}} - {{ settings('app_name', 'News') }}</title>
<meta name="keywords" content="{{ settings('main_keywords', 'News') }}">
<meta name="description" content="{{ settings('main_description', 'News') }}">
@endsection
@section('content')
<section
  class="page-header page-header-modern page-header-background page-header-background-md overlay overlay-color-dark overlay-show overlay-op-7"
  style="background-image: url({{asset('img/page-header-portfolio.jpg')}});">
  <div class="container">
    <div class="row mt-5">
      <div class="col-md-12 align-self-center p-static order-2 text-center">
        <h1 class="text-9 font-weight-bold">{{trans('text.portfolio-index-title')}}</h1>
        <span class="sub-title">{{trans('text.portfolio-index-subtitle')}}</span>
      </div>
    </div>
  </div>
</section>
<div class="container py-2">
  <ul class="nav nav-pills sort-source sort-source-style-3 justify-content-center" data-sort-id="portfolio"
    data-option-key="filter" data-plugin-options="{'layoutMode': 'fitRows', 'filter': '*'}">
    <li class="nav-item active" data-option-value="*">
      <a class="nav-link text-1 text-uppercase active" href="#">
        {{trans('text.portfolio-show-all')}}
      </a>
    </li>
    @foreach ($cats as $cat)
    <li class="nav-item" data-option-value=".cat_{{ $cat->id }}">
      <a class="nav-link text-1 text-uppercase" href="#">
        {{ $cat->name }}
      </a>
    </li>
    @endforeach
  </ul>

  <div class="sort-destination-loader sort-destination-loader-showing mt-4 pt-2">
    <div class="row portfolio-list sort-destination" data-sort-id="portfolio">

      @foreach ($posts as $post)
      <div class="col-md-6 col-lg-4 isotope-item cat_{{ $post->category_id }}">
        @include('portfolio.loop',['post' => $post])
      </div>
      @endforeach
    </div>
  </div>
</div>
@endsection

resources/views/portfolio/loop.blade.php
<div class="portfolio-item">
  <a href="{{ $post->getLink() }}">
    <span class="thumb-info thumb-info-lighten border-radius-0">
      <span class="thumb-info-wrapper border-radius-0">
        <img src="{{ getThumbnail($post->images, 'post_images', 'pf') }}" class="img-fluid border-radius-0" alt="">
        <span class="thumb-info-title">
          <span class="thumb-info-inner">{{ $post->title }}</span>
          <span class="thumb-info-type">{{ $post->getCategoryName() }}</span>
        </span>
        <span class="thumb-info-action">
          <span class="thumb-info-action-icon bg-dark opacity-8"><i class="fas fa-plus"></i></span>
        </span>
      </span>
    </span>
  </a>
</div>

resources/views/portfolio/show.blade.php
@extends('layouts.app')
@section('meta')
<title>{{ $post->title }} - {{ settings('app_name', 'News') }}</title>
<meta name="keywords" content="{{ settings('main_keywords', 'News') }}">
<meta name="description" content="{{ settings('main_description', 'News') }}">
@endsection
@section('content')
<section
  class="page-header page-header-modern page-header-background page-header-background-md overlay overlay-color-dark overlay-show overlay-op-7"
  style="background-image: url({{ asset('img/page-header-portfolio.jpg') }});">
  <div class="container">
    <div class="row mt-5">
      <div class="col">
        <div class="col-md-12 align-self-center p-static order-2 text-center">
          <h1 class="text-9 font-weight-bold">{{ $post->title }}</h1>
          <span class="sub-title">{{ $post->getCategoryName() }}</span>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="container pt-2 pb-4">
  <div class="row pb-4 mb-2">
    <div class="col-md-6 mb-4 mb-md-0 appear-animation" data-appear-animation="fadeInLeftShorter"
      data-appear-animation-delay="300">
      <div class="owl-carousel owl-theme nav-inside nav-inside-edge nav-squared nav-with-transparency nav-dark mt-3"
        data-plugin-options="{'items': 1, 'margin': 10, 'loop': false, 'nav': true, 'dots': false}">
        @foreach ($post->images as $image)
        <div>
          <div class="img-thumbnail border-0 border-radius-0 p-0 d-block">
            <img src="{{ $image->getImage('pj') }}" class="img-fluid border-radius-0" alt="">
          </div>
        </div>
        @endforeach
      </div>
    </div>
    <div class="col-md-6">
      <div class="overflow-hidden">
        <h2 class="text-color-dark font-weight-normal text-4 mb-0 appear-animation" data-appear-animation="maskUp"
          data-appear-animation-delay="600">{{ trans('text.description') }}
          <strong class="font-weight-extra-bold">{{ trans('text.project') }}</strong>
        </h2>
      </div>
      <p class="appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="800">
        {!! $post->body !!}
      </p>
      <div class="overflow-hidden  mt-4">
        <h2 class="text-color-dark font-weight-normal text-4 mb-0 appear-animation" data-appear-animation="maskUp"
          data-appear-animation-delay="1000">{{ trans('text.details') }}
          <strong class="font-weight-extra-bold">{{ trans('text.project') }}</strong>
        </h2>
      </div>
      <ul class="list list-icons list-primary list-borders text-2 appear-animation"
        data-appear-animation="fadeInUpShorter" data-appear-animation-delay="1200">
        <li>
          <i class="fas fa-caret-left right-10"></i>
          <strong class="text-color-primary">{{ trans('text.client') }}:</strong> {{ $post->client }}</li>
        <li>
          <i class="fas fa-caret-left right-10"></i>
          <strong class="text-color-primary">{{ trans('text.date') }}:</strong> {{ $post->date }}</li>
        <li>
          <i class="fas fa-caret-left right-10"></i>
          <strong class="text-color-primary">{{ trans('text.skills') }}:</strong>
          @foreach ($post->getSkills() as $skill)
          <span class="badge badge-dark badge-sm badge-pill px-2 py-1 ml-1">{{ $skill }}</span>
          @endforeach
        </li>
        <li>
          <i class="fas fa-caret-left right-10"></i>
          <strong class="text-color-primary">{{ trans('text.project-url') }}:</strong>
          {{ $post->url }}
        </li>
      </ul>
    </div>
  </div>
</div>
@endsection